name: openmmlab2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.13
  - packaging=24.0
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.10.12
  - python_abi=3.10
  - pyzmq=25.1.2
  - readline=8.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.14.2
  - typing_extensions=4.10.0
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - addict==2.4.0
      - albumentations==1.4.3
      - aliyun-python-sdk-core==2.15.0
      - aliyun-python-sdk-kms==2.16.2
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.2.0
      - crcmod==1.7
      - cryptography==42.0.5
      - cycler==0.12.1
      - fonttools==4.50.0
      - ftfy==6.2.0
      - idna==3.6
      - imageio==2.34.0
      - importlib-metadata==7.1.0
      - jmespath==0.10.0
      - joblib==1.4.0
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - markdown==3.6
      - markdown-it-py==3.0.0
      - matplotlib==3.8.3
      - mdurl==0.1.2
      - mmcv==2.0.0rc4
      - mmengine==0.10.3
      - model-index==0.1.11
      - networkx==3.2.1
      - numpy==1.26.4
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.9.0.80
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.0.37
      - ordered-set==4.1.0
      - oss2==2.17.0
      - pandas==2.2.1
      - pillow==10.2.0
      - prettytable==3.10.0
      - pycocotools==2.0.7
      - pycparser==2.21
      - pycryptodome==3.20.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.28.2
      - rich==13.4.2
      - scikit-image==0.22.0
      - scikit-learn==1.4.2
      - scipy==1.12.0
      - seaborn==0.13.2
      - setuptools==60.2.0
      - tabulate==0.9.0
      - termcolor==2.4.0
      - threadpoolctl==3.4.0
      - tifffile==2024.2.12
      - tomli==2.0.1
      - torch==1.12.0+cu113
      - torchvision==0.13.0+cu113
      - tqdm==4.65.2
      - tzdata==2024.1
      - urllib3==1.26.18
      - yapf==0.40.2
      - zipp==3.18.1
